# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160312_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myurl', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
