# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160319_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 20, 5, 58, 12, 676884, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 20, 5, 58, 29, 106562, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
