# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160320_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ezMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=50)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.URL')),
            ],
        ),
    ]
