# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='mainurl',
            field=models.URLField(default=''),
        ),
    ]
