# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_api_mainurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='da',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='api',
            name='pa',
            field=models.CharField(default='', max_length=3),
        ),
    ]
