# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20160405_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='nofollow',
            field=models.NullBooleanField(),
        ),
    ]
