# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20160405_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='price',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='revenue',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
