# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20160427_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='da',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='api',
            name='pa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
    ]
