# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-04 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20160504_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='da',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='pa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
